### ISSUE TITLE
Wrong Touschek lifetime calculation

### ISSUE THREAD

**Issue by JohnMSmith** [MethodicalAcceleratorDesign/MAD-X#752] opened 2019-03-29 04:07 UTC
For the attached period, different Touschek lifetime values were obtained in MADX, MAD8 and MathCAD - 43h, 39 min, 36 min respectively. To calculate lifetime using MathCAD, parameters from TWISS table calculated in MADX were used. 
For some reason Touscek lifetime isn't calculating properly in MADX.

[MADX files.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/3021079/MADX.files.zip)
[MAD8 files.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/3021025/MAD8.files.zip)
[MathCAD files.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/3021085/MathCAD.files.zip)

**Comment by tpersson** [comment] 2019-03-29 08:51
Thanks for the report and including the test files. 
I started having a look and the calculation which even though rather straightforward, contains a lot of terms.  I am afraid that I don't have a tool to open the MathCAD but maybe we can generate an pdf with the equations? 

The method MAD-X is following seems to be close to (with possible bugs in the code):
https://arxiv.org/pdf/physics/9903034.pdf
The calculations are done in https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/master/src/touschek.f90

It calculates the inverse Touschek for each element (weighted by the length).  My understanding is that the previous method was to average over the TWISS functions and than calculate the lifetime. 

Are you using the same method to calculate the lifetime ? Maybe you can spot something directly from the source file? If not then I will try to go through the equations.

**Comment by JohnMSmith** [comment] 2019-03-29 09:35
In MathCAD I have used Piwinski formalism from the article you attached with weighting as described in MADX User's Manual with CENTER option applied. Here is the web page of MathCAD file 
[Touschek lifetime MathCAD webpage.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/3021842/Touschek.lifetime.MathCAD.webpage.zip)

Source file formulas differ from the original ones. It's not that easy to see a mistake right away.

**Comment by tpersson** [comment] 2019-03-29 13:12
Thanks for the formulas you used. I can see that MAD-X is using different ones while yours seem to follow the paper very closely. It looks to me like you integrate from tau_m to 0.0214. Where do you get that value from? ( In MAD-X the variable substitution is done and the integration goes to pi/2 )

**Comment by tpersson** [comment] 2019-03-29 16:13
The difference is in how the momentum acceptance d_{pm}/p0 (d_{acc} in your calculation ) is calculated in MADX. If I use the same method as you did the script calculates the lifetime to be 36 min. At the moment it is not clear to me why it is calculated in the way it is done in MAD-X. I will investigate further.

**Comment by tpersson** [comment] 2019-04-01 13:17
The issue is fixed in #754 where also the reason for the wrong results is given.

**Closed by tpersson** 2019-04-01 13:17 UTC
Labels: MAD-X
