### ISSUE TITLE
BBORBIT flag not taken into account in track starting from 5.02.09

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#466] opened 2017-09-20 18:38 UTC
The commands `set,-bborbit`, `set,bborbit` have an impact on twiss and no impact on track starting from version 5.02.09 and track does not subtrack the kick of a beam-beam element on the closed orbit.

See attached example [lattice_bborbit.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1318817/lattice_bborbit.txt) and the output files `mad0.datone` `mad.datone`.

A beam-beam element at x=10cm gives a kick at the closed orbit (null in a simple lattice) despite BBORBIT is false

```
NAME   X                 PX       
bb         0                  -6.399811492e-06
```

The behaviour is correct in version <=5.02.08 .

**Comment by ldeniau** [comment] 2017-10-17 15:03
There is no evidence that Track is ignoring the option as the attached file shows. It is possible that Twiss has a side effect on Track (as in many cases), so the Twiss command was put above.
[out5.02.08.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1391484/out5.02.08.txt)
[out5.02.09.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1391485/out5.02.09.txt)
[bborbit.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1391491/bborbit.txt)

**Comment by ldeniau** [comment] 2017-10-18 12:43
[after more than 8 hours of investigation]
There is too many side effects between Track and Twiss for bb elements, with so many globals and injected code inside main loops that this problem is very hard and time consuming to trace and fix for the MAD-X team.

Potential source for the bug is that the bb_kick is not updated by Twiss when called from Track (bizarre logic of internal bbd_flag), giving always zero for ipos and bb_kick (looked at by Track).

Wont be fixed without the help of some expert of this code.

**Comment by ldeniau** [comment] 2017-10-18 15:48
The problem has been identified, but cannot be fixed easily as it has unexpected nasty side effects between specific codes (i.e. SC) and Twiss, the later being supposedly responsible to initialise some global array reused by Track. The SVN revision where the bug was introduced are **5725** (OK) and **5726** (BUG). The changes are minor but the bug arises from the fact that the modules were using the oneturnmap of the previous call (whatever module it was!). Fixing this bug requires to call tmrefe before entering into the module, which in turn call tmfrst which sets global flags and variables for the bbfi submodule. Once set, this seems to not be redone at the phase where it is expected before calling Track and gives invalid results.

As a conclusion, the code enable by bbd_flag needs to be reviewed by an expert to avoid such side effects. Routines like tmrefe tmrefo tmfrst should not depend on how many times they have been called... Unless some unknown flag should be set before calling them to avoid such side effects.

**Comment by ldeniau** [comment] 2017-10-20 08:28
The case in now understood and the behaviour of MAD-X is correct, i.e. it is NOT a bug. In fact it is the fix of a bug that changed the behaviour in the correct manner. Before the bug, i.e. side effects between commands, was giving apparent good results.
The manual will be updated.

**Closed by ldeniau** 2017-10-20 08:28 UTC
Labels: help wanted
